# Generated by Django 4.0.4 on 2022-10-23 13:38

from django.db import migrations, models
import taggit.managers
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('BO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id_creator', models.CharField(default='', max_length=200)),
                ('product_name', models.CharField(default='', max_length=500, verbose_name='Название')),
                ('country', models.CharField(default='', max_length=30, verbose_name='Страна')),
                ('brand', models.CharField(default='', max_length=30, verbose_name='Бренд')),
                ('rate_sum', models.IntegerField(default=0)),
                ('vote_sum', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('category', models.CharField(default='', max_length=50, verbose_name='Категория')),
                ('sex', models.CharField(default='', max_length=50, verbose_name='Категория')),
                ('compound', models.CharField(default='', max_length=50, verbose_name='Срок получения товара')),
                ('size', models.CharField(default='', max_length=300)),
                ('duration', models.CharField(default='', max_length=300)),
                ('price', models.CharField(default=0, max_length=300)),
                ('show_price', models.CharField(default=0, max_length=300)),
                ('description', models.CharField(default='', max_length=1000, verbose_name='Описание')),
                ('availability', models.CharField(default='', max_length=100, verbose_name='')),
                ('amount', models.CharField(default='', max_length=100)),
                ('picture1', models.ImageField(default='https://i.ibb.co/z7zmCKn/2022-08-28-10-00-15.png', upload_to='')),
                ('picture2', models.ImageField(default='https://i.ibb.co/z7zmCKn/2022-08-28-10-00-15.png', upload_to='')),
                ('picture3', models.ImageField(default='https://i.ibb.co/z7zmCKn/2022-08-28-10-00-15.png', upload_to='')),
                ('prevPicture', models.ImageField(default='', upload_to='')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
