# Generated by Django 4.0.4 on 2022-09-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bepartner',
            name='info',
        ),
    ]
