# Generated by Django 4.0.4 on 2022-10-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_buy',
            name='brand',
            field=models.CharField(default='', max_length=200),
        ),
    ]
