# Generated by Django 4.0.4 on 2022-11-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_creator', models.CharField(default='', max_length=200)),
                ('brand', models.CharField(default='', max_length=200)),
                ('id_user_buy', models.CharField(default='', max_length=200)),
                ('price', models.CharField(default='', max_length=200)),
                ('duration', models.CharField(default='', max_length=200)),
                ('compound', models.CharField(default='', max_length=50, verbose_name='Срок получения товара')),
                ('size', models.CharField(default='', max_length=300)),
                ('amount', models.IntegerField()),
                ('product_name', models.CharField(default='', max_length=500)),
                ('status', models.IntegerField(default='0', max_length=200)),
                ('message', models.CharField(default='', max_length=200)),
                ('payment_method', models.CharField(default='картой онлайн', max_length=500)),
                ('img', models.ImageField(default='https://i.ibb.co/z7zmCKn/2022-08-28-10-00-15.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_creator', models.CharField(default='', max_length=200)),
                ('brand', models.CharField(default='', max_length=200)),
                ('id_user_buy', models.CharField(default='', max_length=200)),
                ('price', models.CharField(default='', max_length=200)),
                ('duration', models.CharField(default='', max_length=200)),
                ('compound', models.CharField(default='', max_length=50, verbose_name='Срок получения товара')),
                ('size', models.CharField(default='', max_length=300)),
                ('amount', models.IntegerField()),
                ('product_name', models.CharField(default='', max_length=500)),
                ('status', models.IntegerField(default='0', max_length=200)),
                ('message', models.CharField(default='', max_length=200)),
                ('is_payed', models.BooleanField(default=0)),
                ('delivery_address', models.CharField(default='', max_length=500)),
                ('payment_method', models.CharField(default='картой онлайн', max_length=500)),
                ('order_number', models.BigIntegerField(default='0')),
                ('date_receiving', models.DateField(default='2000-01-01', max_length=50)),
                ('date_add', models.DateField(default='2000-01-01', max_length=50)),
                ('img', models.ImageField(default='https://i.ibb.co/z7zmCKn/2022-08-28-10-00-15.png', upload_to='')),
                ('is_incart', models.BooleanField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Product_buy',
        ),
    ]
