# Generated by Django 4.0 on 2022-03-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='anonymous', max_length=20)),
                ('description', models.CharField(default='-', max_length=500)),
                ('type', models.CharField(default='-', max_length=20)),
                ('delivery', models.CharField(default='-', max_length=20)),
                ('price', models.IntegerField(default='')),
                ('time', models.CharField(default='-', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='anonymous', max_length=20, unique=True)),
                ('password', models.CharField(default='12345678', max_length=20)),
                ('email', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=20)),
                ('surname', models.CharField(default='', max_length=30)),
                ('phone', models.IntegerField(default='')),
                ('city', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Pers',
        ),
    ]
