# Generated by Django 4.0.4 on 2022-09-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_buy',
            name='img',
            field=models.ImageField(default='https://i.ibb.co/s3QmZrw/default.png', upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='product_creator',
            name='picture',
            field=models.ImageField(default='https://i.ibb.co/s3QmZrw/default.png', upload_to='images/product', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='shop',
            name='bgImage',
            field=models.ImageField(default='https://i.ibb.co/s3QmZrw/default.png', upload_to='images/creator/bgImage'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logoImage',
            field=models.ImageField(default='https://i.ibb.co/s3QmZrw/default.png', upload_to='images/creator/logoImage'),
        ),
    ]
