# Generated by Django 4.0.4 on 2022-08-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_buy',
            name='img',
            field=models.ImageField(default='images/default.webp', upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='product_creator',
            name='picture',
            field=models.ImageField(default='images/default.webp', upload_to='images/product', verbose_name=''),
        ),
    ]
