# Generated by Django 4.0.4 on 2022-10-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='id_buyer',
            field=models.CharField(default='', max_length=200),
        ),
    ]
