# Generated by Django 4.0.4 on 2022-09-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0002_alter_product_buy_img_alter_product_creator_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_buy',
            name='removeImg',
            field=models.ImageField(default='https://ibb.co/12Kvkxq/9215d082fddd095c0d7df81f78ce0f2b', upload_to=''),
        ),
        migrations.AddField(
            model_name='product_creator',
            name='removePicture',
            field=models.ImageField(default='https://ibb.co/12Kvkxq/9215d082fddd095c0d7df81f78ce0f2b', upload_to=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='removeBgImage',
            field=models.ImageField(default='https://ibb.co/12Kvkxq/9215d082fddd095c0d7df81f78ce0f2b', upload_to=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='removeLogoImage',
            field=models.ImageField(default='https://ibb.co/12Kvkxq/9215d082fddd095c0d7df81f78ce0f2b', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product_buy',
            name='img',
            field=models.ImageField(default='https://i.ibb.co/s3QmZrw/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product_creator',
            name='picture',
            field=models.ImageField(default='https://i.ibb.co/s3QmZrw/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='shop',
            name='bgImage',
            field=models.ImageField(default='https://i.ibb.co/s3QmZrw/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logoImage',
            field=models.ImageField(default='https://i.ibb.co/s3QmZrw/default.png', upload_to=''),
        ),
    ]
