# Generated by Django 4.0.4 on 2022-10-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0003_remove_cart_product_id_cart_id_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bepartner',
            old_name='phone',
            new_name='shipping_ayndex',
        ),
        migrations.AddField(
            model_name='shop',
            name='shipping_dostavista',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='shop',
            name='shipping_pony_express',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='shop',
            name='shipping_sdek',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='shop',
            name='shipping_yandex_delivery',
            field=models.CharField(default='', max_length=500),
        ),
    ]
