# Generated by Django 4.0.4 on 2022-09-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0003_product_buy_removeimg_product_creator_removepicture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_buy',
            name='removeImg',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product_creator',
            name='removePicture',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='shop',
            name='removeBgImage',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='shop',
            name='removeLogoImage',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
