# Generated by Django 4.0.4 on 2022-08-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0003_shop_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_creator',
            old_name='rating_status',
            new_name='rate_sum',
        ),
        migrations.RenameField(
            model_name='product_creator',
            old_name='term_status',
            new_name='vote_sum',
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.IntegerField(default='1151151515'),
        ),
    ]
