# Generated by Django 4.0.4 on 2022-08-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0003_product_creator_logoimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_creator',
            name='logoImage',
        ),
    ]
