# Generated by Django 4.0.6 on 2022-08-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0004_remove_product_creator_logoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_creator',
            name='subcategory',
            field=models.CharField(default='-', max_length=50, verbose_name='Подкатегория'),
        ),
    ]
