# Generated by Django 4.0.4 on 2022-10-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0004_rename_phone_bepartner_shipping_ayndex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_buy',
            name='status',
            field=models.CharField(default='В обработке', max_length=200),
        ),
    ]
