# Generated by Django 4.0.4 on 2022-08-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0004_rename_rating_status_product_creator_rate_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(default='+15-15-15-15', max_length=20),
        ),
    ]
