# Generated by Django 4.0.6 on 2022-08-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0005_product_creator_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_creator',
            name='subcategory',
        ),
    ]
