# Generated by Django 4.0.4 on 2022-10-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0005_alter_product_buy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_buy',
            name='status',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
