# Generated by Django 4.0.4 on 2022-08-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0005_alter_shop_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='email',
            field=models.CharField(default='example@example.com', max_length=20, unique=True),
        ),
    ]
