# Generated by Django 4.0.4 on 2022-09-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0006_alter_comments_partner_id_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_creator',
            name='amount',
            field=models.CharField(default='', max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
