# Generated by Django 4.0.6 on 2022-08-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0006_remove_product_creator_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_creator',
            old_name='set',
            new_name='size',
        ),
        migrations.AlterField(
            model_name='product_creator',
            name='duration',
            field=models.CharField(default='-', max_length=300),
        ),
    ]
