# Generated by Django 4.0.4 on 2022-09-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0007_product_creator_amount_alter_shop_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_creator',
            name='amount',
            field=models.CharField(default='', max_length=100),
        ),
    ]
