# Generated by Django 4.0.6 on 2022-08-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0007_rename_set_product_creator_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_creator',
            name='compound',
            field=models.CharField(default='-', max_length=50, verbose_name='Срок получения товара'),
        ),
    ]
