# Generated by Django 4.0 on 2022-03-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0007_rename_company_creator_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='anonymous', max_length=50)),
                ('select', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='-', max_length=500)),
                ('price', models.IntegerField(default='')),
                ('time', models.DateField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='creator',
            name='email',
            field=models.CharField(default='example@example.com', max_length=20),
        ),
        migrations.AddField(
            model_name='creator',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
