# Generated by Django 4.0.4 on 2022-10-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0007_alter_product_buy_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='id_buyer',
            new_name='id_user_buy',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='picture1',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='product_buy',
            old_name='payed_partner',
            new_name='is_payed',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='country',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='picture2',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='picture3',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='prevPicture',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='rate_sum',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='show_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='vote_sum',
        ),
        migrations.RemoveField(
            model_name='product_buy',
            name='payed_user',
        ),
        migrations.RemoveField(
            model_name='product_buy',
            name='prevImg',
        ),
        migrations.RemoveField(
            model_name='product_buy',
            name='status_pay',
        ),
        migrations.RemoveField(
            model_name='product_buy',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='date_add',
            field=models.DateField(default='2000-01-01', max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery_address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_payed',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='message',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.IntegerField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='duration',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
