# Generated by Django 4.0.4 on 2022-09-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0008_alter_product_creator_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='bgImage',
            field=models.CharField(default='https://i.ibb.co/s3QmZrw/default.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logoImage',
            field=models.CharField(default='https://i.ibb.co/s3QmZrw/default.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='shop',
            name='prevBgImage',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='shop',
            name='prevLogoImage',
            field=models.CharField(default='', max_length=500),
        ),
    ]
