# Generated by Django 4.0.6 on 2022-08-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0008_product_creator_compound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_creator',
            name='price',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
