# Generated by Django 4.0.4 on 2022-09-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0009_alter_shop_bgimage_alter_shop_logoimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_creator',
            name='picture',
        ),
        migrations.AddField(
            model_name='product_creator',
            name='picture1',
            field=models.ImageField(default='https://i.ibb.co/z7zmCKn/2022-08-28-10-00-15.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='product_creator',
            name='picture2',
            field=models.ImageField(default='https://i.ibb.co/z7zmCKn/2022-08-28-10-00-15.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='product_creator',
            name='picture3',
            field=models.ImageField(default='https://i.ibb.co/z7zmCKn/2022-08-28-10-00-15.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product_buy',
            name='img',
            field=models.ImageField(default='https://i.ibb.co/z7zmCKn/2022-08-28-10-00-15.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='shop',
            name='bgImage',
            field=models.CharField(default='https://i.ibb.co/z7zmCKn/2022-08-28-10-00-15.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logoImage',
            field=models.CharField(default='https://i.ibb.co/z7zmCKn/2022-08-28-10-00-15.png', max_length=500),
        ),
    ]
