# Generated by Django 4.0 on 2022-03-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0010_task_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sample85.jpg', upload_to='images/product'),
        ),
    ]
