# Generated by Django 4.0.4 on 2022-09-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0010_remove_product_creator_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_product',
            name='review',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
