# Generated by Django 4.0.4 on 2022-08-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0010_alter_shop_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='bgImage',
            field=models.ImageField(default='images/default.png', upload_to='images/creator/bgImage'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logoImage',
            field=models.ImageField(default='images/default.png', upload_to='images/creator/logoImage'),
        ),
    ]
