# Generated by Django 4.0.6 on 2022-08-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0010_remove_product_creator_height_packaging_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_creator',
            name='show_price',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
