# Generated by Django 4.0.2 on 2022-09-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0011_alter_comments_product_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='BePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=1000000)),
                ('name', models.CharField(max_length=1000000)),
                ('phone', models.CharField(max_length=1000000)),
                ('city', models.CharField(max_length=1000000)),
                ('link', models.CharField(max_length=1000000)),
                ('info', models.CharField(max_length=1000000)),
            ],
        ),
    ]
