# Generated by Django 4.0.6 on 2022-08-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0011_product_creator_show_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_creator',
            name='sex',
            field=models.CharField(default='-', max_length=50, verbose_name='Категория'),
        ),
    ]
