# Generated by Django 4.0.6 on 2022-08-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0011_alter_shop_bgimage_alter_shop_logoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_buy',
            name='price',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
