# Generated by Django 4.0 on 2022-03-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0012_product_task_id_alter_creator_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='task_id',
        ),
    ]
