# Generated by Django 4.0.6 on 2022-08-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0012_product_buy_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_creator',
            name='duration',
            field=models.CharField(default='-', max_length=50, verbose_name='Срок получения товара'),
        ),
    ]
