# Generated by Django 4.0.6 on 2022-08-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0013_product_creator_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_buy',
            name='duration',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
