# Generated by Django 4.0 on 2022-04-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0013_tag_remove_product_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
