# Generated by Django 4.0.6 on 2022-08-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0014_product_buy_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_product',
            name='id_comentator',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
