# Generated by Django 4.0.6 on 2022-08-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0015_comments_product_id_comentator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments_product',
            old_name='id_comentator',
            new_name='comentator_email',
        ),
    ]
