# Generated by Django 4.0.3 on 2022-04-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0017_alter_product_availability_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost',
            new_name='price',
        ),
    ]
