# Generated by Django 4.0 on 2022-04-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0021_delete_tag_product_creator_tags_task_tags_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parter',
            new_name='Partner',
        ),
    ]
