# Generated by Django 4.0.4 on 2022-05-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0027_comments_partner_comments_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_buy',
            name='date_add',
            field=models.DateField(default='2000-01-01', max_length=50),
        ),
        migrations.AddField(
            model_name='product_buy',
            name='delivery_address',
            field=models.CharField(default='-', max_length=500),
        ),
        migrations.AddField(
            model_name='product_buy',
            name='img',
            field=models.ImageField(default='images/default.png', upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='product_buy',
            name='status_pay',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='product_creator',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product_creator',
            name='rating_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_creator',
            name='term_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partner',
            name='reg_form',
            field=models.CharField(default='Самозанятый', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.DateField(default='2000-01-01', max_length=50),
        ),
    ]
