# Generated by Django 4.0.4 on 2022-05-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0028_product_buy_date_add_product_buy_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_product',
            name='rating',
            field=models.IntegerField(default='0'),
        ),
    ]
