# Generated by Django 4.0.4 on 2022-09-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='userImage',
            field=models.ImageField(default='https://i.ibb.co/s3QmZrw/default.png', upload_to='images/'),
        ),
    ]
