# Generated by Django 4.0.4 on 2022-09-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='removeUserImage',
            field=models.ImageField(default='https://ibb.co/12Kvkxq/9215d082fddd095c0d7df81f78ce0f2b', upload_to=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='userImage',
            field=models.ImageField(default='https://i.ibb.co/s3QmZrw/default.png', upload_to=''),
        ),
    ]
