# Generated by Django 4.0 on 2022-03-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(default='', max_length=40, unique=True),
        ),
    ]
