# Generated by Django 4.0.4 on 2022-09-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_removeuserimage_alter_account_userimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='removeUserImage',
        ),
        migrations.AddField(
            model_name='account',
            name='prevUserImage',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
