# Generated by Django 4.0.4 on 2022-07-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_account_phone_alter_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bik',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='checking_account',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='fiz_adress',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AddField(
            model_name='account',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='korr_check',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='kpp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='ogrn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='street',
            field=models.CharField(default='', max_length=9999),
        ),
    ]
