# Generated by Django 4.0 on 2022-03-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='activity_type',
            field=models.CharField(default='-', max_length=70),
        ),
        migrations.AddField(
            model_name='creator',
            name='is_company',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='creator',
            name='achievements',
            field=models.ImageField(upload_to='images/creator'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='company',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='creator',
            name='cover',
            field=models.ImageField(upload_to='images/creator'),
        ),
    ]
