# Generated by Django 4.0 on 2022-03-26 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0009_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
