# Generated by Django 4.0.3 on 2022-04-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0015_delete_orders_product_id_creator_product_id_user_buy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='height_packaging',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='height_product',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='length_packaging',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='length_product',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='width_packaging',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='width_product',
            field=models.FloatField(default=0),
        ),
    ]
