# Generated by Django 4.0.3 on 2022-04-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0016_product_brand_product_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(default='-', max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='-', max_length=30, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(default='-', max_length=30, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='-', max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height_packaging',
            field=models.FloatField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='height_product',
            field=models.FloatField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='length_packaging',
            field=models.FloatField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='length_product',
            field=models.FloatField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='images/default.png', upload_to='images/product', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='-', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width_packaging',
            field=models.FloatField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='width_product',
            field=models.FloatField(default=0, verbose_name=''),
        ),
    ]
