# Generated by Django 4.0 on 2022-04-12 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0018_rename_cost_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='', max_length=50)),
                ('last_login', models.CharField(default='-', max_length=200)),
                ('username', models.CharField(default='-', max_length=200)),
                ('email', models.CharField(default='-', max_length=200)),
                ('first_name', models.CharField(default='-', max_length=200)),
                ('last_name', models.CharField(default='-', max_length=200)),
                ('country', models.CharField(default='-', max_length=200)),
                ('inn', models.IntegerField(default='0000000000')),
                ('name_small', models.CharField(default='-', max_length=200)),
                ('name_full', models.CharField(default='-', max_length=200)),
                ('reg_form', models.CharField(default='-', max_length=200)),
                ('payment_account', models.CharField(default='-', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product_buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_creator', models.CharField(default='-', max_length=200)),
                ('id_user_buy', models.CharField(default='-', max_length=200)),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status1', models.CharField(default='-', max_length=20)),
                ('status2', models.CharField(default='-', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product_creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_creator', models.CharField(default='-', max_length=200)),
                ('product_name', models.CharField(default='-', max_length=500, verbose_name='Название')),
                ('country', models.CharField(default='-', max_length=30, verbose_name='Страна')),
                ('brand', models.CharField(default='-', max_length=30, verbose_name='Бренд')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('description', models.CharField(default='-', max_length=1000, verbose_name='Описание')),
                ('width_product', models.FloatField(default=0, verbose_name='')),
                ('height_product', models.FloatField(default=0, verbose_name='')),
                ('length_product', models.FloatField(default=0, verbose_name='')),
                ('width_packaging', models.FloatField(default=0, verbose_name='')),
                ('height_packaging', models.FloatField(default=0, verbose_name='')),
                ('length_packaging', models.FloatField(default=0, verbose_name='')),
                ('availability', models.CharField(default='-', max_length=100, verbose_name='')),
                ('picture', models.ImageField(default='images/default.png', upload_to='images/product', verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='activity_type',
        ),
        migrations.AddField(
            model_name='creator',
            name='instagram',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='creator',
            name='published',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='creator',
            name='tag',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='creator',
            name='telegram',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='creator',
            name='vk',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='creator',
            name='whatsapp',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
