# Generated by Django 4.0 on 2022-04-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0019_hashtags_parter_product_buy_product_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_buy',
            name='product_name',
            field=models.CharField(default='-', max_length=500),
        ),
    ]
