# Generated by Django 4.0.4 on 2022-04-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0023_product_creator_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_creator',
            name='product_id',
        ),
    ]
