# Generated by Django 4.0.4 on 2022-05-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0025_product_creator_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='username',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
