# Generated by Django 4.0.4 on 2022-05-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0026_creator_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_creator', models.CharField(default='-', max_length=200)),
                ('id_partner', models.CharField(default='-', max_length=200)),
                ('review', models.CharField(default='-', max_length=200)),
                ('rating', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Comments_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_creator', models.CharField(default='-', max_length=200)),
                ('id_product', models.CharField(default='-', max_length=200)),
                ('review', models.CharField(default='-', max_length=200)),
                ('rating', models.IntegerField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='product_buy',
            name='message',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='product_buy',
            name='payed_partner',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='product_buy',
            name='payed_user',
            field=models.BooleanField(default=0),
        ),
    ]
