# Generated by Django 4.0.4 on 2022-05-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0029_alter_comments_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_creator',
            name='set',
            field=models.CharField(default='-', max_length=300),
        ),
    ]
