# Generated by Django 4.0.4 on 2022-07-05 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0031_chat_room_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_product',
            name='created_data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
