# Generated by Django 4.0.4 on 2022-07-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO', '0032_comments_product_created_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_buy',
            name='status1',
        ),
        migrations.RemoveField(
            model_name='product_buy',
            name='status2',
        ),
        migrations.AddField(
            model_name='product_buy',
            name='status',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
